<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorizationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class AuthorizationRepository extends EntityRepository
{
    public function findCorporationCount($id) {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT count(a) FROM AppBundle:AuthorizationEntity a WHERE a.type = :atype AND a.eveid = :aid'
            )->setParameter('atype', 'C')
            ->setParameter('aid', $id)->getSingleScalarResult();
    }

    public function findAllianceCount($id) {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT count(a) FROM AppBundle:AuthorizationEntity a WHERE a.type = :atype AND a.eveid = :aid'
            )->setParameter('atype', 'A')
            ->setParameter('aid', $id)->getSingleScalarResult();
    }

    public function getCount() {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT count(a) as regCount FROM AppBundle:AuthorizationEntity a WHERE a.eveid != -999'
            )->getSingleScalarResult();
    }

    public function findAllManualAuthorizations() {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:AuthorizationEntity a WHERE a.type != :atype AND a.eveid != -999'
            )->setParameter('atype', 'contact')
            ->getResult();
    }

    public function findAllAutoAuthorizations() {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:AuthorizationEntity a WHERE a.type = :atype'
            )->setParameter('atype', 'contact')
            ->getResult();
    }

    public function getExistingAuthorizations($corporationID, $allianceID) {

        $ids = Array($corporationID, $allianceID);

        return $this->getEntityManager()
            ->createQuery(
                'SELECT a
                      FROM AppBundle:AuthorizationEntity a
                      WHERE a.eveid IN (:ids)'
            )->setParameter('ids', $ids)->getResult();
    }
}
