<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegWhitelistEntityRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RegWhitelistEntityRepository extends EntityRepository
{
    public function findCorporationCount($id) {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT count(p) FROM AppBundle:RegWhitelistEntity p WHERE p.type = :ptype AND p.eveid = :pid'
            )->setParameter('ptype', 'C')
            ->setParameter('pid', $id)->getSingleScalarResult();
    }

    public function findAllianceCount($id) {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT count(p) FROM AppBundle:RegWhitelistEntity p WHERE p.type = :ptype AND p.eveid = :pid'
            )->setParameter('ptype', 'A')
            ->setParameter('pid', $id)->getSingleScalarResult();
    }

    public function getCount() {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT count(p) as regCount FROM AppBundle:RegWhitelistEntity p'
            )->getSingleScalarResult();
    }

}
