<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegWhitelistEntityRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RegWhitelistEntityRepository extends EntityRepository
{
    public function findCorporation($id) {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:RegWhitelistEntity p WHERE p.type > :ptype AND p.eveid = :pid'
            )->setParameter('ptype', 'C')
            ->setParameter('pid', $id)->getResult();
    }

    public function findAlliance($id) {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:RegWhitelistEntity p WHERE p.type > :ptype AND p.eveid = :pid'
            )->setParameter('ptype', 'A')
            ->setParameter('pid', $id)->getResult();
    }
}
